create table person(
                       id bigint generated by default AS IDENTITY PRIMARY KEY ,
                       name varchar(255) not null ,
                       email varchar(255) not null unique ,
                       password varchar(255) not null ,
                       role varchar(50) not null
);
CREATE TABLE Task (
                      id bigint generated by default AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) not null unique,
                      description VARCHAR(255) not null,
                      task_status VARCHAR(50),
                      task_priority VARCHAR(50),
                      author_id INTEGER NOT NULL ,
);
CREATE TABLE task_assignees (
                                task_id bigint,
                                person_id bigint,
                                PRIMARY KEY (task_id, person_id),
                                FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE,
                                FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE
);
CREATE TABLE comment(
    id bigint generated by default as identity primary key ,
    text VARCHAR not null,
    created_at TIMESTAMP,
    task_id INTEGER not null,
    FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE
);

